/*
 * Geocoding
 *
 * With the Geocoding service you can find locations by converting street addresses into GPS-coordinates and vice versa. The Places service allows to search for millions of shops and prominent points of interest in various categories.
 *
 * The version of the OpenAPI document: 1.18
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.geocoding.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.geocoding.Model
{
    /// <summary>
    /// The list of suggested addresses.
    /// </summary>
    [DataContract(Name = "SuggestionsByAddressResponse")]
    public partial class SuggestionsByAddressResponse : IEquatable<SuggestionsByAddressResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuggestionsByAddressResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SuggestionsByAddressResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SuggestionsByAddressResponse" /> class.
        /// </summary>
        /// <param name="suggestions">The list of suggested addresses. (required).</param>
        /// <param name="warnings">A list of warnings concerning the validity of the result..</param>
        public SuggestionsByAddressResponse(List<SuggestedAddress> suggestions = default(List<SuggestedAddress>), List<Warning> warnings = default(List<Warning>))
        {
            // to ensure "suggestions" is required (not null)
            if (suggestions == null)
            {
                throw new ArgumentNullException("suggestions is a required property for SuggestionsByAddressResponse and cannot be null");
            }
            this.Suggestions = suggestions;
            this.Warnings = warnings;
        }

        /// <summary>
        /// The list of suggested addresses.
        /// </summary>
        /// <value>The list of suggested addresses.</value>
        [DataMember(Name = "suggestions", IsRequired = true, EmitDefaultValue = true)]
        public List<SuggestedAddress> Suggestions { get; set; }

        /// <summary>
        /// A list of warnings concerning the validity of the result.
        /// </summary>
        /// <value>A list of warnings concerning the validity of the result.</value>
        [DataMember(Name = "warnings", EmitDefaultValue = false)]
        public List<Warning> Warnings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SuggestionsByAddressResponse {\n");
            sb.Append("  Suggestions: ").Append(Suggestions).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SuggestionsByAddressResponse);
        }

        /// <summary>
        /// Returns true if SuggestionsByAddressResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SuggestionsByAddressResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SuggestionsByAddressResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Suggestions == input.Suggestions ||
                    this.Suggestions != null &&
                    input.Suggestions != null &&
                    this.Suggestions.SequenceEqual(input.Suggestions)
                ) && 
                (
                    this.Warnings == input.Warnings ||
                    this.Warnings != null &&
                    input.Warnings != null &&
                    this.Warnings.SequenceEqual(input.Warnings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Suggestions != null)
                {
                    hashCode = (hashCode * 59) + this.Suggestions.GetHashCode();
                }
                if (this.Warnings != null)
                {
                    hashCode = (hashCode * 59) + this.Warnings.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
