/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding
 * With the Geocoding service you can find locations by converting street addresses into GPS-coordinates and vice versa. The Places service allows to search for millions of shops and prominent points of interest in various categories.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
} from './Location';
import type { Warning } from './Warning';
import {
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * The result of a locations search.
 * @export
 * @interface LocationsSearchResult
 */
export interface LocationsSearchResult {
    /**
     * The found locations.
     * @type {Array<Location>}
     * @memberof LocationsSearchResult
     */
    locations: Array<Location>;
    /**
     * A list of warnings concerning the validity of the result.
     * @type {Array<Warning>}
     * @memberof LocationsSearchResult
     */
    warnings?: Array<Warning>;
}

/**
 * Check if a given object implements the LocationsSearchResult interface.
 */
export function instanceOfLocationsSearchResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "locations" in value;

    return isInstance;
}

export function LocationsSearchResultFromJSON(json: any): LocationsSearchResult {
    return LocationsSearchResultFromJSONTyped(json, false);
}

export function LocationsSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationsSearchResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locations': ((json['locations'] as Array<any>).map(LocationFromJSON)),
        'warnings': !exists(json, 'warnings') ? undefined : ((json['warnings'] as Array<any>).map(WarningFromJSON)),
    };
}

export function LocationsSearchResultToJSON(value?: LocationsSearchResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locations': ((value.locations as Array<any>).map(LocationToJSON)),
        'warnings': value.warnings === undefined ? undefined : ((value.warnings as Array<any>).map(WarningToJSON)),
    };
}

