/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding
 * With the Geocoding service you can find locations by converting street addresses into GPS-coordinates and vice versa. The Places service allows to search for millions of shops and prominent points of interest in various categories.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
} from './Address';
import type { LocationProperties } from './LocationProperties';
import {
    LocationPropertiesFromJSON,
    LocationPropertiesFromJSONTyped,
    LocationPropertiesToJSON,
} from './LocationProperties';
import type { PlaceAllOf } from './PlaceAllOf';
import {
    PlaceAllOfFromJSON,
    PlaceAllOfFromJSONTyped,
    PlaceAllOfToJSON,
} from './PlaceAllOf';
import type { Quality } from './Quality';
import {
    QualityFromJSON,
    QualityFromJSONTyped,
    QualityToJSON,
} from './Quality';
import type { ReferencePosition } from './ReferencePosition';
import {
    ReferencePositionFromJSON,
    ReferencePositionFromJSONTyped,
    ReferencePositionToJSON,
} from './ReferencePosition';
import type { RoadAccessPosition } from './RoadAccessPosition';
import {
    RoadAccessPositionFromJSON,
    RoadAccessPositionFromJSONTyped,
    RoadAccessPositionToJSON,
} from './RoadAccessPosition';

/**
 * 
 * @export
 * @interface Place
 */
export interface Place {
    /**
     * 
     * @type {ReferencePosition}
     * @memberof Place
     */
    referencePosition: ReferencePosition;
    /**
     * 
     * @type {RoadAccessPosition}
     * @memberof Place
     */
    roadAccessPosition?: RoadAccessPosition;
    /**
     * 
     * @type {Address}
     * @memberof Place
     */
    address: Address;
    /**
     * A single string representing the address, typically consisting of the street, house number, postal code, city, and country. The precise format may differ based on what is appropriate for the address.
     * @type {string}
     * @memberof Place
     */
    formattedAddress?: string;
    /**
     * The name of the place.
     * @type {string}
     * @memberof Place
     */
    name?: string;
    /**
     * An array of place category IDs representing the categories this place is assigned to.
     * @type {Array<string>}
     * @memberof Place
     */
    categoryIds: Array<string>;
    /**
     * 
     * @type {Quality}
     * @memberof Place
     */
    quality: Quality;
}

/**
 * Check if a given object implements the Place interface.
 */
export function instanceOfPlace(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "referencePosition" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "categoryIds" in value;
    isInstance = isInstance && "quality" in value;

    return isInstance;
}

export function PlaceFromJSON(json: any): Place {
    return PlaceFromJSONTyped(json, false);
}

export function PlaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Place {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'referencePosition': ReferencePositionFromJSON(json['referencePosition']),
        'roadAccessPosition': !exists(json, 'roadAccessPosition') ? undefined : RoadAccessPositionFromJSON(json['roadAccessPosition']),
        'address': AddressFromJSON(json['address']),
        'formattedAddress': !exists(json, 'formattedAddress') ? undefined : json['formattedAddress'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'categoryIds': json['categoryIds'],
        'quality': QualityFromJSON(json['quality']),
    };
}

export function PlaceToJSON(value?: Place | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'referencePosition': ReferencePositionToJSON(value.referencePosition),
        'roadAccessPosition': RoadAccessPositionToJSON(value.roadAccessPosition),
        'address': AddressToJSON(value.address),
        'formattedAddress': value.formattedAddress,
        'name': value.name,
        'categoryIds': value.categoryIds,
        'quality': QualityToJSON(value.quality),
    };
}

