/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding
 * With the Geocoding service you can find locations by converting street addresses into GPS-coordinates and vice versa. The Places service allows to search for millions of shops and prominent points of interest in various categories.
 *
 * The version of the OpenAPI document: 1.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Warning } from './Warning';
import {
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';
import type { SuggestedAddress } from './SuggestedAddress';
import {
    SuggestedAddressFromJSON,
    SuggestedAddressFromJSONTyped,
    SuggestedAddressToJSON,
} from './SuggestedAddress';

/**
 * The list of suggested addresses.
 * @export
 * @interface SuggestionsByAddressResponse
 */
export interface SuggestionsByAddressResponse {
    /**
     * The list of suggested addresses.
     * @type {Array<SuggestedAddress>}
     * @memberof SuggestionsByAddressResponse
     */
    suggestions: Array<SuggestedAddress>;
    /**
     * A list of warnings concerning the validity of the result.
     * @type {Array<Warning>}
     * @memberof SuggestionsByAddressResponse
     */
    warnings?: Array<Warning>;
}

/**
 * Check if a given object implements the SuggestionsByAddressResponse interface.
 */
export function instanceOfSuggestionsByAddressResponse(value: object): value is SuggestionsByAddressResponse {
    if (!('suggestions' in value) || value['suggestions'] === undefined) return false;
    return true;
}

export function SuggestionsByAddressResponseFromJSON(json: any): SuggestionsByAddressResponse {
    return SuggestionsByAddressResponseFromJSONTyped(json, false);
}

export function SuggestionsByAddressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestionsByAddressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestions': ((json['suggestions'] as Array<any>).map(SuggestedAddressFromJSON)),
        'warnings': json['warnings'] == null ? undefined : ((json['warnings'] as Array<any>).map(WarningFromJSON)),
    };
}

export function SuggestionsByAddressResponseToJSON(value?: SuggestionsByAddressResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'suggestions': ((value['suggestions'] as Array<any>).map(SuggestedAddressToJSON)),
        'warnings': value['warnings'] == null ? undefined : ((value['warnings'] as Array<any>).map(WarningToJSON)),
    };
}

