/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding
 * With the Geocoding service you can find locations by converting street addresses into GPS-coordinates and vice versa. The Places service allows to search for millions of shops and prominent points of interest in various categories.
 *
 * The version of the OpenAPI document: 1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A search text suggested for the input of the searchLocationsByText endpoint.
 * @export
 * @interface Suggestion
 */
export interface Suggestion {
    /**
     * A search address suggestion that can be displayed on a user interface as caption.
     * @type {string}
     * @memberof Suggestion
     */
    caption: string;
    /**
     * An additional address information for the suggestion that can be displayed on a user interface as sub caption.
     * @type {string}
     * @memberof Suggestion
     */
    subCaption: string;
}

/**
 * Check if a given object implements the Suggestion interface.
 */
export function instanceOfSuggestion(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "caption" in value;
    isInstance = isInstance && "subCaption" in value;

    return isInstance;
}

export function SuggestionFromJSON(json: any): Suggestion {
    return SuggestionFromJSONTyped(json, false);
}

export function SuggestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Suggestion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'caption': json['caption'],
        'subCaption': json['subCaption'],
    };
}

export function SuggestionToJSON(value?: Suggestion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'caption': value.caption,
        'subCaption': value.subCaption,
    };
}

