/*
 * Geocoding
 * With the Geocoding service you can find locations by converting street addresses into GPS-coordinates and vice versa. The Places service allows to search for millions of shops and prominent points of interest in various categories.
 *
 * The version of the OpenAPI document: 1.18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.geocoding.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.geocoding.model.AddressScores;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.geocoding.ApiClient;
/**
 * Quality indicators that help deciding how well a result fits to the search input.
 */
@JsonPropertyOrder({
  Quality.JSON_PROPERTY_DISTANCE,
  Quality.JSON_PROPERTY_TOTAL_SCORE,
  Quality.JSON_PROPERTY_ADDRESS_SCORES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-06T09:17:10.827807860Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class Quality {
  public static final String JSON_PROPERTY_DISTANCE = "distance";
  @javax.annotation.Nullable
  private Integer distance;

  public static final String JSON_PROPERTY_TOTAL_SCORE = "totalScore";
  @javax.annotation.Nullable
  private Integer totalScore;

  public static final String JSON_PROPERTY_ADDRESS_SCORES = "addressScores";
  @javax.annotation.Nullable
  private AddressScores addressScores;

  public Quality() { 
  }

  public Quality distance(@javax.annotation.Nullable Integer distance) {
    this.distance = distance;
    return this;
  }

  /**
   * The spatial distance in \\[m\\] between the location or the place and the input of a position search.    This is only available for **searchLocationsByPosition** and **searchPlacesByPosition**.
   * @return distance
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDistance() {
    return distance;
  }


  @JsonProperty(value = JSON_PROPERTY_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistance(@javax.annotation.Nullable Integer distance) {
    this.distance = distance;
  }


  public Quality totalScore(@javax.annotation.Nullable Integer totalScore) {
    this.totalScore = totalScore;
    return this;
  }

  /**
   * An overall score in \\[%\\] for address searches. 100 percent represents a perfect match between the input and the result.    This is only available for **searchLocationsByText** and **searchLocationsByAddress** results.
   * @return totalScore
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalScore() {
    return totalScore;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalScore(@javax.annotation.Nullable Integer totalScore) {
    this.totalScore = totalScore;
  }


  public Quality addressScores(@javax.annotation.Nullable AddressScores addressScores) {
    this.addressScores = addressScores;
    return this;
  }

  /**
   * Get addressScores
   * @return addressScores
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDRESS_SCORES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AddressScores getAddressScores() {
    return addressScores;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS_SCORES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressScores(@javax.annotation.Nullable AddressScores addressScores) {
    this.addressScores = addressScores;
  }


  /**
   * Return true if this Quality object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Quality quality = (Quality) o;
    return Objects.equals(this.distance, quality.distance) &&
        Objects.equals(this.totalScore, quality.totalScore) &&
        Objects.equals(this.addressScores, quality.addressScores);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distance, totalScore, addressScores);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Quality {\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    totalScore: ").append(toIndentedString(totalScore)).append("\n");
    sb.append("    addressScores: ").append(toIndentedString(addressScores)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `distance` to the URL query string
    if (getDistance() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdistance%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDistance()))));
    }

    // add `totalScore` to the URL query string
    if (getTotalScore() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalScore%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalScore()))));
    }

    // add `addressScores` to the URL query string
    if (getAddressScores() != null) {
      joiner.add(getAddressScores().toUrlQueryString(prefix + "addressScores" + suffix));
    }

    return joiner.toString();
  }
}

